---
- name: fqdn | Configure Debian
  include: debian.yml
  when: ansible_distribution in [ 'Debian', 'Ubuntu' ]

- name: fqdn | Configure Redhat
  include: redhat.yml
  when: ansible_distribution in [ 'RedHat', 'CentOS' ]

- name: fqdn | Configure Linux
  include: linux.yml
  when: ansible_system in  [ "Linux" ]

- name: fqdn | Configure Windows
  include: windows.yml
  when: ansible_system in  [ "Win32NT" ]
