---

- name: MasterVM
  hosts:
    - 127.0.0.1
  vars:
    #auth_url: "{{ lookup('env','OS_AUTH_URL') }}"
    # TODO - anti-affinity group must be created manually before running this using "openstack server group create --policy anti-affinity hadoop"
    #hadoop_group_id: "4ad92ce9-7de8-4e9e-b158-23019cb0efc8"
    hadoop_group_id: "a0c23d14-6055-4325-a9ec-8c7342b67e2b"
    host_list:
      - "vlphdc00"
      - "vlphdc01"
      - "vlphdc02"
      - "vlphdc03"
      - "vlphdc04"
      - "vlphdc05"
      - "vlphdc06"
      - "vlphdc07"
      - "vlphdc08"
      - "vlphdc09"
      - "vlphdc10"
      - "vlphdc11"
      - "vlphdc12"
      - "vlphdc13"
      - "vlphdc14"
      - "vlphdc15"
      - "vlphdc16"
    image_id: "7a7af5bf-a86b-4b9e-8ad5-c4e4b1381991"
    host_availability_zone: "us-west-3a"
    vol_availability_zone: "nova"
    private_net: "cona-network1"
    key_name: "cona_admin"
  tasks:
   - name: Create Volumes
     os_volume:
      size: 512
      volume_type: "volumes_hdd"
      state: present
      availability_zone: "{{ vol_availability_zone }}"
      timeout: 500
      display_name: "{{ item[0] }}_v{{ item[1] }}"
     with_nested:
       - "{{ host_list }}"
       - [ 1, 2, 3 ]
   - name: Create VMs
     os_server:
      #auth:
        #auth_url: "{{ auth_url }}"
      state: present
      availability_zone: "{{ host_availability_zone }}"
      name: "{{ item }}"
      image: "{{ image_id }}"
      key_name: "{{ key_name }}"
      timeout: 500
      nics:
        - net-name: "{{ private_net }}"
      # TODO/HACK use a smaller instance flavor and assign a floating(public) IP to the first host only
      flavor: "{% if item.endswith('00') %}m3.medium{% else %}m3.2xlarge{% endif %}"
      auto_ip: "{% if item.endswith('00') %}yes{% else %}no{% endif %}"
      security_groups:
        - "default"
        - "Allow SSH"
      terminate_volume: "no"
      scheduler_hints: "group={{ hadoop_group_id }}"
      meta:
        hostname: "{{ item }}"
        group: "hadoop"
      volumes:
        - "{{ item }}_v1"
        - "{{ item }}_v2"
        - "{{ item }}_v3"
     with_items: "{{ host_list }}"

- name: Add Virtustream Yum repos
  hosts: hadoop
  become: yes
  roles:
    - virtustream

- name: Set Hostname
  vars:
    domain_name: "cokeonena.com"
  hosts: hadoop
  become: yes
  roles:
    - role: ansible-fqdn
      fqdn: "{{ ansible_hostname }}.{{ domain_name }}"
      hostname: "{{ ansible_hostname }}"

- name: Create disks
  hosts: hadoop
  become: yes
  roles:
    - datavol
