---

# Looks like there are two ways to install ambari. EPEL or manual repo
#- name: Needed for accelerated mode
#  hosts: hadoop
#  become: yes
#  roles:
#    - { role: geerlingguy.repo-epel }
#  tasks:
#    - yum: name=python-keyczar state=latest
#    - service: name=iptables state=stopped enabled=no
#    - lineinfile: state=present create=yes dest=/etc/sudoers.d/888-dont-requiretty line="Defaults !requiretty" backup=yes

- name: Get Sun JDK
  hosts: hadoop
  become: yes
  roles:
    - name: get Sun JDK installed
      role: "williamyeh.oracle-java"
      java_version: 7
      java_subversion: 80
      java_download_from_oracle: true
      java_install_jce: true    # ambari need JCE
      java_set_javahome: true

- name: Apply common configuration to all target nodes
  hosts: hadoop
  become: yes
  roles:
    - common

#- name: Ambari repo
  #hosts: hadoop
  #become: yes
  #roles:
    #- ambari-repo

#- name: Ambari server
  #hosts: ambari
  #become: yes
  #roles:
    #- ambari-server

#- name: Ambari agent
  #hosts: hadoop
  #become: yes
  #roles:
    #- ambari-agent

  #- name: run the blueprint
  #hosts: ambari
  #become: yes
  #roles:
  #  - blueprint
