---
galaxy_info:
    author: Roman Gorodeckij
    description: Set FQDN and hostname
    license: MIT
    min_ansible_version: 1.7
    platforms:
        - name: EL
          versions:
              - all
        - name: Ubuntu
          versions:
              - all
        - name: Debian
          versions:
              - all
        - name: Windows
          versions:
              - all
    categories:
        - networking
        - system

dependencies: []

